# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 00:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(default='', max_length=500)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 14, 19, 19, 55, 796000), null=True)),
                ('correo', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'comentario',
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Independiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('foto', models.CharField(max_length=200)),
                ('experiencia', models.IntegerField()),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=30)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio')),
            ],
            options={
                'db_table': 'independiente',
                'verbose_name': 'independiente',
                'verbose_name_plural': 'independientes',
            },
        ),
        migrations.AddField(
            model_name='comentario',
            name='independiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='independiente.Independiente'),
        ),
    ]
